from collections.abc import Callable, Mapping

__version__: str

def init(settings: dict[str, str | bool | int], cache_dir: str, profile_dir: str, log: Callable[[int, str], None]) -> None: ...

def update_settings(updates: Mapping[str, str | bool | int]) -> None: ...

class AuthError(Exception): ...
class LoginInvalidError(Exception): ...
class LoginEmptyError(Exception): ...
class RefreshTokenError(Exception): ...
class NetworkError(Exception): ...
class GraphQLError(Exception): ...
class ParseError(Exception): ...
class RateLimitError(Exception): ...
class NotFoundError(Exception): ...
