from collections.abc import Iterable, Mapping
from typing import Literal, TypeVar

_T = TypeVar("_T")

def reformat_image_url(url: str | None) -> str: ...
def url_to_program(url: str) -> str: ...
def play_url_to_id(url: str) -> dict[Literal["video_id", "video_url", "whatson_id", "episode_id"], str]: ...
def shorten_link(url: str | None) -> str | None: ...
def find_entry(dict_list: Iterable[Mapping[str, _T]], key: str, value: _T) -> Mapping[str, _T] | None: ...
def youtube_to_plugin_url(url: str) -> str: ...
